### ISSUE TITLE
Android full screen support

### ISSUE THREAD

**Issue by KestasVenslauskas** [THEOplayer/react-native-theoplayer#13]
Looking at the android native source there is no actual full screen support.
Setting an activity to immersive mode and hiding system bar is just a part of it.
But what happens if I have a video player that is small on the screen? Or what if I have a scroll view with few players?
Current example does not reflect actual player usage within the app unless you app is only having a video on a single screen.

Since there is no native controls it's impossible (or maybe not?) to add native full screen support as for now, but here is some inspiration from other projects.

JWPlayer
Fullscreen implementation by moving player view to activity root content layout (which I tested on your player and it works great but since there is no controls it's not a solution for now).
https://github.com/chaimPaneth/react-native-jw-media-player/blob/365977b4bbe23695cc996f40c4e5da0cf4fbc7e4/android/src/main/java/com/appgoalz/rnjwplayer/RNJWPlayerView.java#L372

AVPlayer
Fullscreen player dialog popup:
https://github.com/expo/expo/blob/main/packages/expo-av/android/src/main/java/expo/modules/av/video/FullscreenVideoPlayer.java

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas true, on Android the fullscreen sets the immersive mode flags for your activity. The actual SDK's fullscreen mode would start a new activity with the fullscreen player. As the React-Native UI is tied to the original activity, it wouldn't be visible here anymore.

There are a few options. The easiest is to make sure the player view in ReactNative is covering the whole screen first before setting the fullscreen (immersive) mode. Either by navigating to a new RN page that only contains the THEOplayerView component, or stretching the current THEOplayerView component.

Another option is using the Android's web-based SDK, as shown in https://github.com/THEOplayer/react-native-theoplayer/tree/experiment/android-basic-minapi21. This is a web-based SDK that would behave the same as on iOS. It has the advantages it contains a full (web-based) UI with also fullscreen mgmt. The downsides are that it has the downsides of using a webview, less performance, and you need to setup different SDKs for android mobile, androidTV & fireTV.

Finally, the native UI for our Unified Android SDK is still under development, and coming in the next months. Once this is available the native UI could be used instead of a RN UI.

**Comment by KestasVenslauskas** [comment]
@tvanlaerhoven 
Is there any progress on this? Because as of now there is no way to toggle fullscreen mode on android in any way.
