### ISSUE TITLE
When screen is off and PIP is playing, phone gets really hot and drains battery fast

### ISSUE THREAD

**Issue by davidwinograd1** [THEOplayer/react-native-theoplayer#178]
We are using react-native-theoplayer, and a recent issue has arisen when playing a video, the screen is off and PIP is playing, the phone gets really hot and drains the battery fast. 

We were wondering if any recent update of react-native-theoplayer has contributed to this, and what a possible solution would be.

Using version 2.11...

**Comment by tvanlaerhoven** [comment]
@davidwinograd1 on which platform you are experiencing this issue?
On Android we had one change regarding the PiP UI (https://github.com/THEOplayer/react-native-theoplayer/blob/develop/CHANGELOG.md#changed), but I'm not sure it could cause this behaviour.

Did you see this only in the current 2.11 version?

**Comment by davidwinograd1** [comment]
Have any other users complained about this? @tvanlaerhoven

**Comment by tvanlaerhoven** [comment]
@davidwinograd1 No it hasn't been reported yet. We'll check it internally.

**Comment by tvanlaerhoven** [comment]
@davidwinograd1 We have indeed identified an issue and raised an internal ticket.

**Comment by ceyhun-o** [comment]
Hi @davidwinograd1,

As I mentioned [on our Service Desk](https://opentelly.atlassian.net/browse/THEOSD-13454), we have found the root cause of this issue and fixed it. It was due to an internal defect on the core iOS SDK that happened when the player went into PiP. It wasn’t related to locking the screen afterwards, going to PiP was enough to trigger the high CPU usage.

Please update to the latest version of our RN SDK and also make sure that you are using 6.2.0 for iOS.

Kind regards,
Ceyhun
