### ISSUE TITLE
Android: device goes to sleep mode while video is playing

### ISSUE THREAD

**Issue by KestasVenslauskas** [THEOplayer/react-native-theoplayer#28]
On android while video is still playing device locks itself (goes to sleep).
I'm not sure if this is intended but maybe we can have a configurable field to keep screen alive while video is playing?

**Comment by Danesz** [comment]
Hi @KestasVenslauskas ,

The player does not acquire the wakelock automatically. (because there is no "one fit for all" solution)

You can acquire the wakelock on application level yourself in multiple ways on Android level:
https://developer.android.com/training/scheduling/wakelock

or on React level:
https://www.npmjs.com/package/react-native-wake-lock

Let me know if this helps.



Best regards,
Daniel

**Comment by KestasVenslauskas** [comment]
@Danesz As I meantioned maybe it's a feture request for a configurable param as "keepScreenAlive":boolean

**Comment by KestasVenslauskas** [comment]
Yes using external libraries could save time for now.
