### ISSUE TITLE
Update on the older issues?

### ISSUE THREAD

**Issue by KestasVenslauskas** [THEOplayer/react-native-theoplayer#48]
I did not wanted to make a new issue but no one is responding inside the older issues...

Is there any update regarding those issues?
Fullscreen support - https://github.com/THEOplayer/react-native-theoplayer/issues/13
Controls for android - https://github.com/THEOplayer/react-native-theoplayer/issues/11

**Comment by tvanlaerhoven** [comment]
Hey @KestasVenslauskas , indeed we missed your comments on the closed ticket.

The Android UI is launched in Q1. It will be added as an optional dependency and enabled with the `chromeless` flag, just like on other platforms. For now we are limited on Android to the UI included in the example app.

Fullscreen support is also closely tied to the native UI. Because an extra activity is launched in fullscreen mode, we need to have some native controls here to be able to return to the inline player view. Fullscreen/immersive play-out is currently possible, but only if the RN screen that goes into fullscreen contains only the player view. This is because we set the fullscreen/immersive flags on the whole activity.

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas that would be Q1 of 2023, which will indeed contain a procedure of going to fullscreen that is consistent across all platforms.
Besides that we are also considering using a dialog approach for fullscreen, in addition to the option of launching a separate activity.
